name: microblogging
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.6
  firebase_auth: ^0.16.1
  provider: ^4.1.3
  dio: ^3.0.9
  sliding_up_panel: ^1.0.2
  mask_text_input_formatter: ^1.0.7
  cloud_functions: ^0.5.0
  firebase_messaging: ^6.0.16
  flushbar: ^1.10.4
  google_sign_in: 4.5.5
  get_it: ^3.1.0
  equatable: ^1.0.1
  dartz: ^0.8.9
  data_connection_checker: ^0.3.4
  http: ^0.12.0+3
  font_awesome_flutter:
  cached_network_image:


dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.2.0
  mockito: ^4.1.1
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Inter-BoldItalic.ttf
          weight: 700



